#aruqivo aonde eu vou criar a semente para criação de massas

#fazerndo require do md5 para criptrografar a senha
require "digest/md5"

#preciso fazer require relative em tudo que não for do cucumber
require_relative "features/support/libs/mongo"

#metodo para receber a senha e retornar no formato md5
def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :seeds do
  #o arquivo não consegue ter as informações do cucumber
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))
  users = [
    { name: "Teste Login", email: "teste@login.com", password: to_md5("teste123") },
    { name: "Teste Remover", email: "teste@remover.com", password: to_md5("teste123") },
  ]
  #chamo o metodo do drop danger do mongo para excluir o banco
  MongoDb.new.drop_danger
  #chamo o metodo do insert para poder adicionar os usuarios no banco
  MongoDb.new.insert_users(users)

  #para fazer o rake rodar o cucumber
  #   sh "cucumber"
end

# para executar o arquivo no terminal digitar rake com o nome da task
#no nosso caso seeds
